apiVersion: charts.intel.com/v1alpha1
kind: Ovms
metadata:
  name: ovms-sample
spec:
  image_name: openvino/model_server:latest
  service_type: LoadBalancer
  replicas: 1
  target_device: CPU
  log_level: DEBUG

  ##  Model repository in S3 or compat store
  # Name of k8s secret containing access/secret keypair
  s3_secret_name: "s3-auth"
  # Used to for buckets in Amazon S3
  s3_region: "us-east-1"
  # Used for non-Amazon S3 endpoints
  #s3_endpoint: ""

  ## Model repository in Google Cloud Storage
  #
  #gcs_secret_name: ""

  ## Path to model repository,
  # S3 style URI, eg.
  model_path: "s3://bucket/models/human-pose-estimation-0001"
  # Google Cloud Storage URI
  #model_path: "gs://models"

  # Name of model to serve, eg.
  model_name: "human-pose-estimation"
