# permissions for end users to view ovms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovms-viewer-role
rules:
- apiGroups:
  - charts.intel.com
  resources:
  - ovms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.intel.com
  resources:
  - ovms/status
  verbs:
  - get
